### PR TITLE
Add average keystrokes per day plot 📈📊

### PR DESCRIPTION
**Pull request by ElDeveloper**
The main plot space now includes a line to show the average keystrokes for that week, the user can click on the line to see the value there represented.

pr

Note that the weekly averages in this context are defined as the total number of keystrokes for a given week, divided by the number of distinct days (instead of always dividing by seven).

### CODE REVIEW

**Comment by ElDeveloper** [comment]
This PR still needs to update the README with a new animated GIF.

**Comment by ElDeveloper** [comment]
Compiled version with this merged branch is now available at:

http://cl.ly/3X1Y1i1j2d13

cc @lkursell

**Comment by lkursell** [comment]
Installed!

Noticed that if the app didn’t register any keystrokes on a day, it fails to display that day indicator:

**Comment by ElDeveloper** [comment]
Hmmm, that's strange. Would you mind opening a new issue and perhaps
adding a screenshot? I thought I got rid of this problem a while ago.

**Pull request merged**
