### PR TITLE
Update to use CorePlot 2.0

### LINKED ISSUE #16: App crashes in 10.11 🚢
After upgrading to 10.11, you will no longer be able to open Keystats, this seems to be due to a problem with CorePlot, that's been reported and fixed, see this issue https://github.com/core-plot/core-plot/issues/210. We need to update the codebase to use CorePlot 2 and everything should work afterwards.

### PR DESCRIPTION
**Pull request by ElDeveloper**
This fixes #16 (keystats crashing on El Capitán :ship: :anchor: ).

### CODE REVIEW

**Comment by highacid** [comment]
how do i open this build? to download it

**Comment by ElDeveloper** [comment]
The way to download this would be using github and pulling down this branch, would have to be something along the lines of:

```bash
git clone github.com/eldeveloper/keystats.git
git checkout -b fix
git pull origin fix
# open xcode and compile
```

However, the build I uploaded to the other issue is the one as generated by this branch.

**Comment by highacid** [comment]
➜  Desktop  git clone github.com/eldeveloper/keystats.git
fatal: repository 'github.com/eldeveloper/keystats.git' does not exist

**Comment by highacid** [comment]
➜  Desktop  git clone http://github.com/ElDeveloper/keystats.git
Cloning into 'keystats'...
remote: Counting objects: 1615, done.
remote: Total 1615 (delta 0), reused 0 (delta 0), pack-reused 1615
Receiving objects: 100% (1615/1615), 13.05 MiB | 4.33 MiB/s, done.
Resolving deltas: 100% (829/829), done.
Checking connectivity... done.

**Pull request merged**
